<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hanin Almodaweb">

<title>An Exploration of Trends in Crime Rates Across Los Angeles (2020-2024)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="LA Crime Report_files/libs/clipboard/clipboard.min.js"></script>
<script src="LA Crime Report_files/libs/quarto-html/quarto.js"></script>
<script src="LA Crime Report_files/libs/quarto-html/popper.min.js"></script>
<script src="LA Crime Report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="LA Crime Report_files/libs/quarto-html/anchor.min.js"></script>
<link href="LA Crime Report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="LA Crime Report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="LA Crime Report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="LA Crime Report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="LA Crime Report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="LA Crime Report_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="LA Crime Report_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">An Exploration of Trends in Crime Rates Across Los Angeles (2020-2024)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hanin Almodaweb </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Los Angeles (LA), a sprawling metropolis known for its diversity and global cultural influence, has a complex history of crime that has evolved alongside the city’s rapid growth. From the early 20th century, when organized crime syndicates and Prohibition-era bootlegging plagued its streets, to the racially charged tensions and gang violence that emerged in the post-World War II period, LA’s criminal landscape has mirrored the social, economic, and demographic changes of the city.</p>
<p>At the center of this history is the Los Angeles Police Department (LAPD), which has faced its own challenges. The LAPD has a complex history shaped by corruption scandals, strained community relations, and efforts at reform. From the 1950s through the 1990s, LAPD leadership emphasized professional policing but often operated in isolation from democratic regulation and community relationships, particularly in marginalized areas like South LA. High-profile incidents such as the Rodney King beating in 1991 and the Rampart corruption scandal in the late 1990s exposed systemic issues within the department, prompting significant reforms aimed at fostering community policing and improving transparency by allowing the public to access real-time information. Apps such as Citizen and platforms like the USC Department of Public Safety’s Crime Alerts are key tools in this shift and have prompted this analysis.</p>
<p>In light of this backdrop, this analysis uses the <a href="https://data.lacity.org/Public-Safety/Crime-Data-from-2020-to-Present/2nrs-mtv8/about_data">LAPD’s Crime Data</a> from 2020 to the present to explore crime incidence and distribution across LA. The dataset provides a comprehensive view of reported crimes, offering insights into trends by geographic areas, crime types, and victim demographics. This analysis aims to shed light on how crime is evolving in the city and to better understand the distribution and impact of crime in different communities.</p>
<section id="primary-questions-of-interest" class="level3">
<h3 class="anchored" data-anchor-id="primary-questions-of-interest">Primary Questions of Interest</h3>
<p><span style="color: #660099;"> <em>How have crime rates changed across different geographic areas in Los Angeles (LA) from 2020 to 2024, and what trends can be observed in terms of the age, sex, and descent of victims?</em> </span></p>
</section>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<section id="dataset-background" class="level4">
<h4 class="anchored" data-anchor-id="dataset-background">Dataset Background</h4>
<p>The data used for this analysis was obtained from the Los Angeles Open Data Portal, specifically the “Crime Data from 2020 to Present” dataset. This dataset is maintained by the LAPD and provides comprehensive records of crime incidents reported in the city since 2020. Accessing the data involved navigating to the Public Safety section of the Los Angeles City Data Catalog where the dataset is publicly available for download. The data was exported as a CSV file, which was subsequently imported into R for further analysis and exploration. This dataset was chosen for its breadth of information, allowing for detailed analysis of crime incidence and distribution in LA, which is pertinent to understanding public safety in the area.</p>
<p>In this dataset, 986,500 observations (rows) of 28 variables (columns) capture details about crime incidents in the LA area. Each row represents an individual crime incident, and the variables include details such as the crime type, area name, and geographic coordinates, as well as key victim details such as age, sex, and descent. The dataset also includes timestamps and codes related to the modus operandi, which enable an in-depth analysis of crime patterns, regional concentrations, and demographic trends in the 2020-2024 timeframe under study.</p>
</section>
<section id="data-cleaning-and-wrangling" class="level4">
<h4 class="anchored" data-anchor-id="data-cleaning-and-wrangling">Data Cleaning and Wrangling</h4>
<p>To clean and prepare the crime dataset for analysis, several steps were taken to ensure the data was clear, interpretable, and ready for data analysis. Upon loading the dataset, an initial exploration was performed, which involved checking the dataset’s dimensions, inspecting the names and types of variables, and checking for any missing cases among the variables of interest. Next, I specified the variables of interest for further analysis, including DATE.OCC (date crime occurred), TIME.OCC (time crime occured), AREA (area code), AREA.NAME (area name), Crm.Cd (crime code), Vict.Age (age of victim), Vict.Sex (sex of victim), and Vict.Descent (descent of victim). I conducted a missing value analysis for these variables to ensure data integrity, with results presented in a summary table. I noted that the crime codes Crm.Cd.1 through Crm.Cd.4 had substantial missing values, with Crm.Cd.1 showing only 11 missing entries, while the others had missing values exceeding 900,000. Given that these variables would not contribute meaningful insights into crime severity trends, I excluded them from my analysis.</p>
<p>Subsequent data wrangling involved converting the DATE.OCC variable to a date-time object and extracting the year. I defined specific crime codes for violent and property crimes, creating categorical variables to classify crime types and categorized crmes with codes tat were not specified in the dataset manual as “other” to account for all crimes reported. The Vict.Age variable was recoded to indicate no victim involved when the age was zero, leading to the creation of a new variable that distinguished between cases with and without a victim. Additionally, I established age categories to account for the variability in victim ages, and recoded the descent and sex variables into clearer categories. To group areas into broader regions, I categorized the AREA.NAME variable into specific bureaus based on <a href="https://www.lapdonline.org/office-of-the-chief-of-police/office-of-special-operations/detective-bureau/crime-mapping-and-compstat/">LAPD crime mapping</a>.</p>
<p>Throughout the cleaning process, I updated the list of variables of interest, removing any variables that were irrelevant or had excessive missing values, particularly those related to additional crime codes that provided no insightful information regarding crime severity trends. The final dataset included the following variables of interest: crime code, year, crime category, specific crime category, victim involvement, victim sex, region, victim descent, and victim age.</p>
<p>I addressed implausible values during the cleaning phase, filtering out any entries where Victim_Age was less than 0 or greater than 99. The cleaned dataset contained 986,367 observations and 11 variables. I confirmed the categorization of crimes and other attributes, noting that the missing values primarily occurred for cases where the age was recorded as zero, indicating no victim was involved.</p>
</section>
<section id="data-exploration" class="level4">
<h4 class="anchored" data-anchor-id="data-exploration">Data Exploration</h4>
<p>To analyze crime trends in LA from 2020 to 2024, I summarized key variables using descriptive statistics compiled into tables for clear visualization. I addressed the primary research question by displaying the total crime count for each year from 2020 to 2024, including percent change year-over-year (Table 1). Next, I focused on the geographic distribution of crimes (Table 2). I computed the total crime count for each area, allowing me to identify regions with the highest and lowest crime counts By organizing this data by region, I could visualize how crime was concentrated in specific areas and track changes over time. Lastly, I examined victim demographics. I calculated counts given the nature of the outcome variable, observing patterns in victim age group (Table 3), descent (Table 4), and sex (Table 5) to see if certain demographic groups were disproportionately affected by crimes in LA between the years 2020 and 2024.</p>
</section>
<section id="table-1.-crime-rate-summary-by-year-2020-2024" class="level3">
<h3 class="anchored" data-anchor-id="table-1.-crime-rate-summary-by-year-2020-2024">Table 1. Crime Rate Summary by Year (2020-2024)</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 1: Crime Rate Summary by Year (2020-2024)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: right;" data-quarto-table-cell-role="th">Year</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Crime Count</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Percent Change (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">199755</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">209763</td>
<td style="text-align: right;">5.01</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">235140</td>
<td style="text-align: right;">12.10</td>
</tr>
<tr class="even">
<td style="text-align: right;">2023</td>
<td style="text-align: right;">232163</td>
<td style="text-align: right;">-1.27</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2024</td>
<td style="text-align: right;">109546</td>
<td style="text-align: right;">-52.82</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>As shown in <em>Table 1</em>, the total crime count increased from 199,755 in 2020 to a peak of 235,140 in 2022, before experiencing a notable decline in subsequent years, particularly a drastic decrease of 52.82% in 2024.</p>
</section>
<section id="table-2.-geographic-distribution-summary-by-year-2020-2024." class="level3">
<h3 class="anchored" data-anchor-id="table-2.-geographic-distribution-summary-by-year-2020-2024.">Table 2. Geographic Distribution Summary by Year (2020-2024).</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 2: Geographic Distribution Summary by Year (2020-2024)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Region</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Crime Count</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Average Crime Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Central Bureau</td>
<td style="text-align: right;">240883</td>
<td style="text-align: right;">48176.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Bureau</td>
<td style="text-align: right;">207136</td>
<td style="text-align: right;">41427.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Valley Bureau</td>
<td style="text-align: right;">287462</td>
<td style="text-align: right;">57492.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">West Bureau</td>
<td style="text-align: right;">250886</td>
<td style="text-align: right;">50177.2</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><em>Table 2</em> indicates that the Valley Bureau recorded the highest total crime count of 287,462, while the South Bureau had the lowest average crime count, suggesting geographical disparities in crime distribution.</p>
</section>
<section id="table-3.-number-of-crimes-by-age-group." class="level3">
<h3 class="anchored" data-anchor-id="table-3.-number-of-crimes-by-age-group.">Table 3. Number of Crimes by Age Group.</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 3: Number of Crimes by Age Group
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Age Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Crime Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Child (1-12)</td>
<td style="text-align: right;">8248</td>
</tr>
<tr class="even">
<td style="text-align: left;">Teen (13-18)</td>
<td style="text-align: right;">23183</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Young Adult (19-25)</td>
<td style="text-align: right;">106174</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adult (26-35)</td>
<td style="text-align: right;">204506</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Middle-Aged (36-50)</td>
<td style="text-align: right;">208459</td>
</tr>
<tr class="even">
<td style="text-align: left;">Senior (51-65)</td>
<td style="text-align: right;">125216</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elderly (66-99)</td>
<td style="text-align: right;">49160</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The age distribution of crime victims, detailed in <em>Table 3</em>, highlights that middle-aged individuals (ages 36-50) are the most frequently victimized age group, with 208,459 incidents reported, followed closely by adults (ages 26-35) at 204,506. Collectively, these two age groups account for over 412,000 crimes.</p>
</section>
<section id="table-4.-number-of-crimes-by-victim-descent." class="level3">
<h3 class="anchored" data-anchor-id="table-4.-number-of-crimes-by-victim-descent.">Table 4. Number of Crimes by Victim Descent.</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 4: Number of Crimes by Victim Descent
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Victim Descent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Crime Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hispanic/Latino/Mexican</td>
<td style="text-align: right;">288250</td>
</tr>
<tr class="even">
<td style="text-align: left;">White</td>
<td style="text-align: right;">183155</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Black</td>
<td style="text-align: right;">132896</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other</td>
<td style="text-align: right;">63761</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other Asian</td>
<td style="text-align: right;">20746</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: right;">16640</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Korean</td>
<td style="text-align: right;">5692</td>
</tr>
<tr class="even">
<td style="text-align: left;">Filipino</td>
<td style="text-align: right;">4572</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chinese</td>
<td style="text-align: right;">4323</td>
</tr>
<tr class="even">
<td style="text-align: left;">Japanese</td>
<td style="text-align: right;">1503</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vietnamese</td>
<td style="text-align: right;">1122</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Indian/Alaskan Native</td>
<td style="text-align: right;">979</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asian Indian</td>
<td style="text-align: right;">537</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pacific Islander</td>
<td style="text-align: right;">278</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hawaiian</td>
<td style="text-align: right;">177</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cambodian</td>
<td style="text-align: right;">88</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Laotian</td>
<td style="text-align: right;">73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guamanian</td>
<td style="text-align: right;">72</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Samoan</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unspecified</td>
<td style="text-align: right;">32</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>In terms of victim descent, <em>Table 4</em> illustrates that Hispanic/Latino/Mexican individuals represent the largest group of victims, with a total of 288,250 crimes reported, followed by White and Black victims.</p>
</section>
<section id="table-5.-number-of-crimes-by-victim-sex." class="level3">
<h3 class="anchored" data-anchor-id="table-5.-number-of-crimes-by-victim-sex.">Table 5. Number of Crimes by Victim Sex.</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 5: Number of Crimes by Victim Sex
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Victim Sex</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Crime Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Male</td>
<td style="text-align: right;">364857</td>
</tr>
<tr class="even">
<td style="text-align: left;">Female</td>
<td style="text-align: right;">349829</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: right;">10119</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: right;">141</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><em>Table 5</em> reveals a slight male predominance among crime victims, with 364,857 male victims compared to 349,829 female victims, while the number of victims classified as “Other” or “Unknown” remains relatively low.</p>
</section>
</section>
<section id="preliminary-results" class="level1">
<h1>Preliminary Results</h1>
<section id="figure-1.-trend-of-crime-count-in-la-over-time-2020-2024." class="level3">
<h3 class="anchored" data-anchor-id="figure-1.-trend-of-crime-count-in-la-over-time-2020-2024.">Figure 1. Trend of Crime Count in LA Over Time (2020-2024).</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LA-Crime-Report_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 1</em> graphically represents the trends described in <em>Table 1</em>, which summarizes the crime count and percent change for Los Angeles from 2020 to 2024. As shown in the table, crime rates rose steadily from 199,755 in 2020 to a peak of 235,140 in 2022, reflecting a 12.1% increase in that year alone. This upward trend is captured in the line chart, where crime levels rise continuously through 2022. However, the decline in crime becomes more apparent in 2023, with a modest decrease of 1.27%. Both the table and figure highlight the most dramatic shift in 2024, where the crime count dropped by 52.82%, reaching 109,546. The sudden and steep decline shown in the chart aligns with the table’s data, indicating a sharp reduction in criminal activity in 2024 compared to previous years.</p>
</section>
<section id="figure-2.-crime-counts-by-year-and-region-in-los-angeles." class="level3">
<h3 class="anchored" data-anchor-id="figure-2.-crime-counts-by-year-and-region-in-los-angeles.">Figure 2. Crime Counts by Year and Region in Los Angeles.</h3>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LA-Crime-Report_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 2</em> highlights the yearly crime trends across four regions in Los Angeles—Central Bureau, South Bureau, Valley Bureau, and West Bureau—from 2020 to 2024. Each region shows a slight downward trend in total crime over time, as indicated by the black trend lines. The Valley Bureau consistently records the highest crime counts, exceeding 75,000, while the West Bureau has the lowest, staying below 50,000. Both the Central and South Bureaus exhibit moderate crime levels, with small fluctuations but a general decline over the five years.</p>
</section>
<section id="figure-3.-crime-count-by-year-and-crime-category." class="level3">
<h3 class="anchored" data-anchor-id="figure-3.-crime-count-by-year-and-crime-category.">Figure 3. Crime Count by Year and Crime Category.</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LA-Crime-Report_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 3</em> illustrates the distribution of total crimes in Los Angeles across three categories—Other, Property Crime, and Violent Crime—from 2020 to 2024. Property and violent crimes exhibit relatively stable trends from 2020 to 2023, with both categories consistently contributing large portions of total crimes each year. However, in 2024, there is a sharp decline across all categories, with “Other” crimes experiencing the steepest drop.</p>
<p>Property crimes generally account for the highest crime counts each year, followed by violent crimes, which maintain a steady but slightly lower contribution. “Other” crimes consistently show lower counts compared to the other categories. The data suggests that crime rates were stable until 2023, after which all categories saw significant reductions, particularly in 2024.</p>
</section>
<section id="figure-4.-crime-category-by-region-in-los-angeles." class="level3">
<h3 class="anchored" data-anchor-id="figure-4.-crime-category-by-region-in-los-angeles.">Figure 4. Crime Category by Region in Los Angeles.</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LA-Crime-Report_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 4</em> shows the distribution of Property Crime, Violent Crime, and Other Crimes across four regions in Los Angeles. Property Crime is the most common category, with the Valley Bureau reporting the highest count and the South Bureau the lowest. Violent Crime is relatively consistent, with the South Bureau leading and the West Bureau reporting the fewest. Other Crimes are highest in the Valley Bureau and lowest in the South Bureau. Overall, the Valley Bureau has the highest crime counts across all categories.</p>
</section>
<section id="table-6.-crime-counts-by-region-and-crime-category." class="level3">
<h3 class="anchored" data-anchor-id="table-6.-crime-counts-by-region-and-crime-category.">Table 6. Crime Counts by Region and Crime Category.</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 6: Crime Counts by Region and Crime Category
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Crime Category</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Central Bureau</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">South Bureau</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Valley Bureau</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">West Bureau</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Property Crime</td>
<td style="text-align: right;">109578</td>
<td style="text-align: right;">76806</td>
<td style="text-align: right;">137828</td>
<td style="text-align: right;">129152</td>
</tr>
<tr class="even">
<td style="text-align: left;">Violent Crime</td>
<td style="text-align: right;">74366</td>
<td style="text-align: right;">77755</td>
<td style="text-align: right;">71914</td>
<td style="text-align: right;">59861</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: right;">56939</td>
<td style="text-align: right;">52575</td>
<td style="text-align: right;">77720</td>
<td style="text-align: right;">61873</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><em>Table 6</em> highlights that the Valley Bureau reports the highest crime counts across all categories, with 137,828 property crimes, 71,914 violent crimes, and 77,720 other crimes.</p>
</section>
<section id="table-7.-crime-counts-by-area-in-valley-bureau." class="level3">
<h3 class="anchored" data-anchor-id="table-7.-crime-counts-by-area-in-valley-bureau.">Table 7. Crime Counts by Area in Valley Bureau.</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 7: Crime Counts by Area in Valley Bureau
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Area Name</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Crime Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N Hollywood</td>
<td style="text-align: right;">50193</td>
</tr>
<tr class="even">
<td style="text-align: left;">Van Nuys</td>
<td style="text-align: right;">42052</td>
</tr>
<tr class="odd">
<td style="text-align: left;">West Valley</td>
<td style="text-align: right;">41443</td>
</tr>
<tr class="even">
<td style="text-align: left;">Devonshire</td>
<td style="text-align: right;">40972</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Topanga</td>
<td style="text-align: right;">40586</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission</td>
<td style="text-align: right;">39571</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Foothill</td>
<td style="text-align: right;">32645</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Given the highest total crime count is in the valley bureau, <em>Table 7</em> presents area-specific crime counts within the bureau. This table shows that North Hollywood has the highest crime count (50,193), followed by Van Nuys (42,052) and West Valley (41,443). Other areas, such as Devonshire (40,972), Topanga (40,586), Mission (39,571), and Foothill (32,645), also contribute significantly to the overall crime in the region.</p>
</section>
<section id="table-8.-summary-table-of-violent-crime-count-over-the-years-2020-2024." class="level3">
<h3 class="anchored" data-anchor-id="table-8.-summary-table-of-violent-crime-count-over-the-years-2020-2024.">Table 8. Summary Table of Violent Crime Count Over the Years (2020-2024).</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th colspan="7" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 8: Summary of Violent Crimes with Percent Change (2020-2024)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Specific Crime Category</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2020</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2021</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2022</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2023</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2024</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Percent Change (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Aggravated Assault</td>
<td style="text-align: right;">18562</td>
<td style="text-align: right;">20080</td>
<td style="text-align: right;">20175</td>
<td style="text-align: right;">20002</td>
<td style="text-align: right;">5569</td>
<td style="text-align: right;">-70.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Homicide</td>
<td style="text-align: right;">356</td>
<td style="text-align: right;">402</td>
<td style="text-align: right;">392</td>
<td style="text-align: right;">330</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">-73.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rape</td>
<td style="text-align: right;">1588</td>
<td style="text-align: right;">1641</td>
<td style="text-align: right;">1618</td>
<td style="text-align: right;">1446</td>
<td style="text-align: right;">328</td>
<td style="text-align: right;">-79.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">Robbery</td>
<td style="text-align: right;">8019</td>
<td style="text-align: right;">8499</td>
<td style="text-align: right;">9118</td>
<td style="text-align: right;">8686</td>
<td style="text-align: right;">2728</td>
<td style="text-align: right;">-65.98</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Simple Assault</td>
<td style="text-align: right;">34607</td>
<td style="text-align: right;">34355</td>
<td style="text-align: right;">37200</td>
<td style="text-align: right;">37578</td>
<td style="text-align: right;">10523</td>
<td style="text-align: right;">-69.59</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><em>Table 8</em> shows a significant decline across all categories of violent crime from 2020 to 2024. The most dramatic reduction is seen in rape cases, which dropped by 79.35%, followed by homicides with a 73.60% decrease. Aggravated assault and simple assault also fell sharply by 70.00% and 69.59%, respectively. Robbery experienced the least reduction but still declined substantially by 65.98%. Overall, the data reveals a consistent downward trend in violent crimes, with each category experiencing a decrease of over 65% by 2024.</p>
</section>
<section id="table-9.-summary-table-of-property-crime-count-over-the-years-2020-2024." class="level3">
<h3 class="anchored" data-anchor-id="table-9.-summary-table-of-property-crime-count-over-the-years-2020-2024.">Table 9. Summary Table of Property Crime Count Over the Years (2020-2024).</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th colspan="7" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 9: Summary of Property Crimes with Percent Change (2020-2024)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Specific Crime Category</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2020</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2021</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2022</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2023</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2024</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Percent Change (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Burglary</td>
<td style="text-align: right;">13755</td>
<td style="text-align: right;">13017</td>
<td style="text-align: right;">14986</td>
<td style="text-align: right;">15303</td>
<td style="text-align: right;">4656</td>
<td style="text-align: right;">-66.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Motor Vehicle Theft</td>
<td style="text-align: right;">21341</td>
<td style="text-align: right;">24349</td>
<td style="text-align: right;">25455</td>
<td style="text-align: right;">25963</td>
<td style="text-align: right;">18561</td>
<td style="text-align: right;">-13.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other Theft</td>
<td style="text-align: right;">22711</td>
<td style="text-align: right;">23842</td>
<td style="text-align: right;">28068</td>
<td style="text-align: right;">33680</td>
<td style="text-align: right;">20896</td>
<td style="text-align: right;">-7.99</td>
</tr>
<tr class="even">
<td style="text-align: left;">Personal Theft</td>
<td style="text-align: right;">1085</td>
<td style="text-align: right;">1115</td>
<td style="text-align: right;">2103</td>
<td style="text-align: right;">2275</td>
<td style="text-align: right;">1266</td>
<td style="text-align: right;">16.68</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Theft from Vehicle</td>
<td style="text-align: right;">27662</td>
<td style="text-align: right;">29656</td>
<td style="text-align: right;">32386</td>
<td style="text-align: right;">30767</td>
<td style="text-align: right;">18466</td>
<td style="text-align: right;">-33.24</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><em>Table 9</em> shows a notable decline in several categories of property crime from 2020 to 2024. Burglary experienced the most significant reduction, decreasing by 66.15%, while theft from vehicles fell by 33.24%. Motor vehicle theft declined by 13.03% after peaking in 2022, and other thefts dropped by 7.99% following a peak in 2023. Conversely, personal theft increased by 16.68% before a decline in 2024. Overall, the data indicates a downward trend in most property crime categories, with burglary showing the largest decrease.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>In conclusion, this report highlights significant changes in crime rates across different geographic areas of Los Angeles, revealing patterns in the age, sex, and descent of victims. The findings provide meaningful insights into the fluctuations in crime over the past 5 years. The total crime count rose from 199,755 in 2020 to a peak of 235,140 in 2022 before experiencing a drastic decline of 52.82% in 2024. Geographically, the Valley Bureau recorded the highest total crime count, while the South Bureau had the lowest average crime count, indicating notable disparities in crime distribution. The age distribution analysis showed that middle-aged individuals (ages 36-50) and adults (ages 26-35) were the most frequently victimized, with over 412,000 incidents reported among these groups. Victims identified as Hispanic/Latino/Mexican constituted the largest demographic, totaling 288,250 crimes, followed by White and Black victims. A slight male predominance was observed, with 364,857 male victims compared to 349,829 female victims. The data depicted in the tables and figures consistently illustrates an overall downward trend in both property and violent crimes from 2020 to 2024, especially pronounced in 2024. Violent crime categories showed significant reductions, particularly in rape and homicide, while property crimes also experienced declines, with burglary reflecting the most substantial decrease. Although crime rates overall have shown a downward trajectory, certain categories, such as personal theft, indicate ongoing challenges that require focused attention. Thus, the figures and tables successfully addressed the primary question by identifying key trends and patterns in crime across different regions and demographic groups in Los Angeles.</p>
<p>The observed trends in crime rates across Los Angeles from 2020 to 2024 can be attributed to various interrelated factors. Economic conditions play a significant role; the peak in crime during 2022 likely correlated with financial instability resulting from the COVID-19 pandemic, while the subsequent decline in 2024 may reflect economic recovery and improved employment opportunities. Additionally, community policing initiatives and enhanced law enforcement strategies aimed at fostering trust between police and residents may have effectively deterred criminal activity. The availability of social services, such as youth engagement programs and mental health support, can also mitigate factors contributing to crime, particularly in vulnerable populations. Furthermore, demographic shifts, particularly among Hispanic/Latino/Mexican communities, highlight the importance of addressing specific social dynamics that impact crime victimization. Overall, these complex factors underscore the necessity of targeted, data-driven approaches to crime prevention that address both the symptoms and root causes of crime in Los Angeles.</p>
<section id="future-consderations" class="level4">
<h4 class="anchored" data-anchor-id="future-consderations">Future Consderations</h4>
<p>As crime trends in Los Angeles continue to evolve, several pertinent questions arise that warrant further exploration. One critical area is the impact of socioeconomic status on crime victimization and perpetration, particularly among different demographic groups. Investigating how factors such as income level, education, and employment status intersect with age, sex, and descent could yield valuable insights into the underlying causes of crime. Additionally, it would be worthwhile to examine the effectiveness of specific community policing strategies across diverse neighborhoods and how these initiatives influence crime rates and community trust in law enforcement.</p>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ul>
<li>Crime mapping and Compstat. LAPD Online. (August 29, 2024). https://www.lapdonline.org/office-of-the-chief-of-police/office-of-special-operations/detective-bureau/crime-mapping-and-compstat/</li>
<li>Fagan, Jeffrey and MacDonald, John, Policing, Crime and Legitimacy in New York and Los Angeles: The Social and Political Contexts of Two Historic Crime Declines (August 21, 2012). Columbia Public Law Research Paper No.&nbsp;12-315, Available at SSRN: https://ssrn.com/abstract=2133487 or http://dx.doi.org/10.2139/ssrn.2133487</li>
<li>Los Angeles Open Data Portal. (February 10, 2020). Crime Data from 2020 to Present. Los Angeles. https://data.lacity.org/Public-Safety/Crime-Data-from-2020-to-Present/2nrs-mtv8/about_data</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>